import '../models/carboot_sale.dart';

class CarBootRepository {
  // Mock data for London car boot sales
  Future<List<CarBootSale>> getCarBootSales() async {
    // Simulate network delay
    await Future.delayed(const Duration(seconds: 1));

    return [
      CarBootSale(
        id: '1',
        name: 'Bermondsey Market Car Boot',
        location: 'Bermondsey',
        address: 'Bermondsey Square, London SE1 3UN',
        date: DateTime.now().add(const Duration(days: 2)),
        openingTime: '06:00',
        closingTime: '14:00',
        latitude: 51.4994,
        longitude: -0.0831,
        estimatedSize: 150,
        facilities: ['Toilets', 'Food', 'Parking', 'ATM'],
        rating: 4.5,
        reviewCount: 127,
        description: 'Historic antiques and bric-a-brac market in the heart of Bermondsey. Great for vintage finds and unique treasures.',
        organiser: 'Bermondsey Square Events',
        contactEmail: 'info@bermondseysquare.com',
        isVerified: true,
      ),
      CarBootSale(
        id: '2',
        name: 'Pimlico Road Farmers Market Car Boot',
        location: 'Pimlico',
        address: 'Orange Square, Pimlico Road, London SW1W 8UT',
        date: DateTime.now().add(const Duration(days: 1)),
        openingTime: '09:00',
        closingTime: '13:00',
        latitude: 51.4891,
        longitude: -0.1547,
        estimatedSize: 80,
        facilities: ['Toilets', 'Food', 'Disabled Access'],
        rating: 4.2,
        reviewCount: 89,
        description: 'Community-focused car boot sale with a sustainable ethos. Perfect for finding eco-friendly bargains.',
        organiser: 'Pimlico Community Group',
        contactEmail: 'hello@pimlicomarket.org',
        isVerified: true,
      ),
      CarBootSale(
        id: '3',
        name: 'Wimbledon Stadium Car Boot Sale',
        location: 'Wimbledon',
        address: 'Plough Lane, London SW17 0BL',
        date: DateTime.now().add(const Duration(days: 3)),
        openingTime: '07:00',
        closingTime: '16:00',
        latitude: 51.4260,
        longitude: -0.1909,
        estimatedSize: 300,
        facilities: ['Toilets', 'Food', 'Parking', 'ATM', 'Disabled Access'],
        rating: 4.7,
        reviewCount: 234,
        description: 'One of London\'s largest car boot sales. Huge variety of items from household goods to collectibles.',
        organiser: 'Wimbledon Stadium Events',
        contactEmail: 'events@wimbledonstadium.co.uk',
        isVerified: true,
      ),
      CarBootSale(
        id: '4',
        name: 'Battersea Boot Fair',
        location: 'Battersea',
        address: 'Battersea Technology College, Battersea Park Road, London SW8 4LY',
        date: DateTime.now().add(const Duration(days: 7)),
        openingTime: '08:00',
        closingTime: '15:00',
        latitude: 51.4769,
        longitude: -0.1414,
        estimatedSize: 120,
        facilities: ['Toilets', 'Food', 'Parking'],
        rating: 4.1,
        reviewCount: 156,
        description: 'Popular weekend car boot sale near Battersea Park. Great atmosphere and friendly sellers.',
        organiser: 'South London Car Boots',
        contactEmail: 'info@southlondoncarboots.com',
        isVerified: false,
      ),
      CarBootSale(
        id: '5',
        name: 'Crystal Palace Car Boot',
        location: 'Crystal Palace',
        address: 'Crystal Palace National Sports Centre, Ledrington Road, London SE19 2BB',
        date: DateTime.now().add(const Duration(days: 4)),
        openingTime: '07:30',
        closingTime: '14:30',
        latitude: 51.4180,
        longitude: -0.0755,
        estimatedSize: 200,
        facilities: ['Toilets', 'Food', 'Parking', 'Disabled Access'],
        rating: 4.4,
        reviewCount: 198,
        description: 'Large car boot sale in the grounds of the National Sports Centre. Excellent for families.',
        organiser: 'Crystal Palace Events Ltd',
        contactEmail: 'carboot@crystalpalace.co.uk',
        isVerified: true,
      ),
      CarBootSale(
        id: '6',
        name: 'Greenwich Market Car Boot',
        location: 'Greenwich',
        address: 'Greenwich Market, College Approach, London SE10 9HZ',
        date: DateTime.now().add(const Duration(days: 5)),
        openingTime: '09:00',
        closingTime: '17:00',
        latitude: 51.4816,
        longitude: -0.0080,
        estimatedSize: 100,
        facilities: ['Toilets', 'Food', 'Disabled Access'],
        rating: 4.6,
        reviewCount: 312,
        description: 'Historic market location with a mix of car boot stalls and artisan sellers. Great for unique finds.',
        organiser: 'Greenwich Market',
        contactEmail: 'info@greenwichmarket.london',
        isVerified: true,
      ),
      CarBootSale(
        id: '7',
        name: 'Elephant & Castle Car Boot',
        location: 'Elephant & Castle',
        address: 'New Kent Road, London SE1 6TE',
        date: DateTime.now().add(const Duration(days: 6)),
        openingTime: '06:30',
        closingTime: '13:00',
        latitude: 51.4948,
        longitude: -0.0958,
        estimatedSize: 90,
        facilities: ['Toilets', 'Food'],
        rating: 3.9,
        reviewCount: 67,
        description: 'Early morning car boot sale perfect for bargain hunters. Local community atmosphere.',
        organiser: 'SE1 Community Markets',
        contactEmail: 'markets@se1community.org',
        isVerified: false,
      ),
      CarBootSale(
        id: '8',
        name: 'Tooting Car Boot Sale',
        location: 'Tooting',
        address: 'Tooting Common, London SW17 8RG',
        date: DateTime.now().add(const Duration(days: 8)),
        openingTime: '08:00',
        closingTime: '15:00',
        latitude: 51.4467,
        longitude: -0.1631,
        estimatedSize: 160,
        facilities: ['Toilets', 'Food', 'Parking', 'ATM'],
        rating: 4.3,
        reviewCount: 145,
        description: 'Community car boot sale on the common with a focus on sustainable living and upcycling.',
        organiser: 'Tooting Common Events',
        contactEmail: 'events@tootingcommon.org',
        isVerified: true,
      ),
    ];
  }

  Future<CarBootSale?> getCarBootSaleById(String id) async {
    final sales = await getCarBootSales();
    try {
      return sales.firstWhere((sale) => sale.id == id);
    } catch (e) {
      return null;
    }
  }
}
